version: "3.3"
services:
  mysql:
      image: mysql
      restart: always
      environment:
        MYSQL_DATABASE: 'db'
        # So you don't have to use root, but you can if you like
        # MYSQL_USER: 'OpenSpy'
        # You can use whatever password you like
        # MYSQL_PASSWORD: 'OpenSpy'
        # Password for root access
        MYSQL_ROOT_PASSWORD: password
        MYSQL_ROOT_HOST: '%'
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
      expose:
          - '3306'
        # Where our data will be persisted
      volumes:
        - mysqldb-data:/var/lib/mysql
  seeder:
      build: './docker-compose-support/mysql-seed'
      environment:
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'password'
        MYSQL_HOST: 'mysql'
        HTTP_API_URL: 'core-web:8080'
        RABBITMQ_HOST: "rabbit"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"
        HTTP_API_KEY: "GDuBqPLVPio/G6x43dG2nHUCOq29IWOxO8SiqRsnZp/S7HiWj+f0Q3wfgsgLZjuW7zjR11xjUNp3Bwwxo+OhQg98Uegu2PJI5/8zuiq3+kGhiy/y0W5T/VWJqYIHBIkS3DgiWhmD8ce9u69kzXhXdSrGol8KVmXF7712W949tJmzvQKQ77kAzu71eboqfztE8NMQGZ9VVsVyFiy76ujj1ah8uRkF+zpAilLQJjV56kLvRtLxqWF078B3Nh9MfckplT1+2i25ZZhRB//qIwxTTYZGq/UvYIrV+Snp/wkOcyIyTvXArkE2Jw3B8mhYIEGGv0sxaUwQvcPEa5v4Vlr8PQ=="
      # links:
      #   - mysql
      #   - rabbit
      #   - core-web
      volumes:
        - "./sql:/sql"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: OpenSpy
      MONGO_INITDB_ROOT_PASSWORD: OpenSpy123

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "LXTXGOZZDFGDBWNGILHM"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    volumes:
      - "./docker-compose-support/enabled_plugins:/etc/rabbitmq/enabled_plugins"
  core-web:
    image: "chcniz/openspy-web-backend"
    hostname: "core-web"
    restart: on-failure
    depends_on:
      - rabbit
      - mongo
      - redis
      - mysql
    ports:
      - "8080:8080"
    environment:
      CONNECTIONSTRINGS__REDISCACHE: "redis:6379,allowAdmin=true"
      CONNECTIONSTRINGS__GAMEMASTERDB: "server=mysql;database=Gamemaster;user=root;password=password"
      CONNECTIONSTRINGS__GAMETRACKERDB: "server=mysql;database=GameTracker;user=root;password=password"
      CONNECTIONSTRINGS__KEYMASTERDB: "server=mysql;database=KeyMaster;user=root;password=password"
      CONNECTIONSTRINGS__PEERCHATDB: "server=mysql;database=Peerchat;user=root;password=password"
      CONNECTIONSTRINGS__RMQCONNECTION: "amqp://rabbitmq:rabbitmq@rabbit1:5672/"
      CONNECTIONSTRINGS__SNAPSHOTDB: "mongodb://openspy:OpenSpy123@mongo:27017/gamestats"
      APIKeyPrivateKey: "MIIEowIBAAKCAQEAzXTtYaYDwBUC6Gg51A9LQcymVe3dON4Ge67SoToIxVhpMwURraJXB0eg6aSvkMQdLJaKPDbx6dfqr0XEzhMBZRQ6wwsDbvAHjlTSP4BfSQMXCoNYDzKAGqovy+V+Rx2riTdtUyDjmyWc1l+RI7pEyLrBj98QKEZh/aJcCUutdET/lnjue7iWCwmJJJZmth7gSfq4laQCDD07QACcv7g4wWzedzSDfLeLfO5H1RxdhidkfF+cbBmAh51yMIy9efvbwRSWAVmGyz8C/5cET7Zj1MyjhurFIgnTRz/pCWwveLPzENfcIAEmj0j7DAMhx/26lUUV6N0qh7AQcQJexmAHuQIDAQABAoIBAQC+9R5s09BIhz7co4KcBlr8HSm8VAh5AmMkMaizES11vmaIdP2pVGlu6rQ0dEx5UM2M055HuQm/Pl9x6Hay0hdJyzOSdHoMciuTrmJ7guUNB0IzE0CVX2qRXfxuli54CquULV//E2J4oMzUsp5DhqzHpEyjW7+4rzIEexLv0Na2aH/werMXBE6V6PxyeW5nKSAZWqYL7sZUP3Pe79xpMFIeXrCLr3UjMWAGPHfGzVBgtNQqzK35As04z5ut+XhgNAO3uIx2kb7QdazCnJZ5EysNlyDZYGpaq90qJoTr2oRialQk3nEFEjNnNo74cXwLWKcx+j5vO2TYcxj7y5fEWPsBAoGBAPI/vpjbb49PYphEUpriKdyUWY1ab6wwvyxbVZd+kxGfIuCr54Yom974sIsdVSz9eKDmrYQArEBMD/OgM9QXPU5YhVoRO1m59jNwiUI3/gZne0FfKh3zgEojrOP3Fcc2kP+jVUH4FTGZ9Gsdjt1cdnO8ZkBERaQuNPorbx4TgbEtAoGBANkeiLFoX7s933vShbEyVjg3kW+ol09SbHkleeJiPkE69uG1peImjmErseB6bf4+Sc84OOJDjCg+qMbcpfJ9hdlHOM6rVZAcBlFOU0A4OdxQdfiUR6oYDSrncTMfye6xboGWDDodr98y4mwYJNUkxHVnJ2PCEilmwwhbV9xevhA9AoGAPUKLc2JCgu4jU7grX4mD5okJYGqXROcK4S+zpFzY2iLxEfnG0bFhQXCITJW9XWQ35hCPnosBBD135zcDBEZgNXjDODSVWqphLT7vJvS742i1zaFAKFTUg2skJH3uXvNYlZz7SXRv/5wcKB5Qa4AfYEMrZGMfbVZWBVGIhwWNzX0CgYAkBzARmEtCa9r41g8/PyYVgAsPJz+sdvXvCGv4R+siseEjxRu4skMwFqsWn9o+tSFUVHUD/sd0Kimhjh2vZmreijX//WheWHgn58JixrG7QFLDI//cVs9gjjU3kY/VnvXCZR60ShbUB8KQw1ThVY+QF8TuhdazrgyxB09GDyak1QKBgEA0nFPLqHAZ05eFL35JVebknP5+kysfRP6viMy9HMplVNslZVGK52fJ8fzViyntjyVHmADPalxLF7gKjtQQob/Wm+zrMQOEeR7dbICm2IqfgeKcaBhXKRWbifKxUEVEiKZYimPuDm317o7apxeVh6eJauKpkPZe1UM+uXsGor6X"
      PresencePreAuthPrivateKey: "MIIBOgIBAAJBAO1aRNQrw2iKAKiKwvu1lDZUpklFmqg2V8RgD3nK8a0kJSIYkJ7XeZt46pp9WSUV4ZekxVc2ogIS9VNZ8fpZMFMCAwEAAQJAcASUS1ZEKQhIe0LR9x2hT2rv99DDxvOuxF1ZsG9ZVA68U0hdLZuApqWNiLADW5dUoniyCzpOpObsgYHCuozREQIhAPaO9rfb/NrM9tQ+gLRW1DLcBLADfSCTz41KOORQV029AiEA9nEPNCMB90RzQP/JoB/TmZAHZ/I89UMcpJn0G9CUr08CIHVmoafugjoVOrrZgCNe7O/CwCCnqJ8ogr2+R9S/RLLpAiBCtlZkSbnFgw0kIlolc5gncNrgY63mwvUlBdwUD4HAdwIhANlbalfPp3NAkjTKaoRTR7CFp9a5y2+f1FkySKB1AcB1"
      ASPNETCORE_ENVIRONMENT: "development"
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      

volumes:
  mysqldb-data: